name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      - name: Install Protoc
        uses: arduino/setup-protoc@v3.0.0
        with:
          version: "33.1"
          repo-token: ${{ secrets.GH_PAT }}
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.15.2
        with:
          toolchain: stable
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
